### ISSUE TITLE
MED P: 'Loading' copy on start screen

### ISSUE THREAD

**Issue by Chilladelphia** [amoliski/ATraleTaleVue#4]
Add small "loading" copy to start screen— add a blinking animator to show that it is active

**Comment by amoliski** [comment]
Mind adding it to figma so I know where it goes?

**Comment by Chilladelphia** [comment]
Yes. I'll add it in tonight at the hotel!

**Comment by Chilladelphia** [comment]
I imagine that it looks a bit like  this. @amoliski 

<img width="460" alt="Screen Shot 2022-04-04 at 12 47 40 AM" src="https://user-images.githubusercontent.com/22155350/161475820-38e7e938-c6e4-432a-895f-48e2948a96fb.png">
